#!/bin/busybox sh

# create links for all busybox commands
for i in $(/bin/busybox --list)
 do
  /bin/busybox ln -s /bin/busybox /bin/$i
  /bin/busybox ln -s /bin/busybox /sbin/$i
   
done

echo "Mounting Stuff"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs -o size=10 tmpfs/tmp

echo "Starting mdev"
mdev -s

# execut custom initprogramm (sysinfo)
/bin/main
sleep 5

ifconfig  eth0 up
udhcpc -i eth0 -s /usr/share/udhcpc/sample.script
httpd -h /www/ &
chmod 777 /www/cgi-bin/*

echo "17" > /sys/class/gpio/export
echo "in" > /sys/class/gpio17/direction


# exec /bin/runled5 &
exec /bin/led5 &

exec /bin/sh
exit 0
